### ISSUE TITLE
[website] Connect Strapi to the static generation

### ISSUE THREAD

**Issue by developersteve** [Lilypad-Tech/web-ui#109]
using the `staging` branch connect the deployed strapi instance up to the github action responsible for the static site generation from the deployment flow. 

To test it, add in a few of the site homepage text elements so that they are generated from the strapi instance during the build process and check that they are deployed to the staging site.

**Comment by developersteve** [comment]
For the first integration, can you please connect up from the 2nd panel on the homepage the mission statement text

```We create an AI-driven decentralized network that uses underutilized resources to make efficient, sustainable technology accessible to everyone.```

**Comment by bonhokage06** [comment]
Hi sir, we can use Strapi now. This is the sample result.Thank you

![image](https://github.com/user-attachments/assets/b80ea3dc-76a0-4e8f-9227-e4a6633989e8)
