### ISSUE TITLE
[website] [strapi] home page logo image collection

### ISSUE THREAD

**Issue by developersteve** [Lilypad-Tech/web-ui#111]
Add media upload and output for the `trusted by` homepage section so that each logo/image for this section can get uploaded to strapi and outputted as part of the build process. 

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/469c4747-ed93-4e5d-ab1c-5617adef1c18">

Also include a text input for `alt title` for each image. 

Out of scope for this round is handling image resizing.

**Comment by developersteve** [comment]
Also link that into the subpages (like at the bottom of the ./team page) , if its not already as a common widget element type.

**Comment by bonhokage06** [comment]
hi sir @developersteve Already updated this one. Is there an updated logos that we can use for each entry? thank you

**Comment by developersteve** [comment]
@bonhokage06 Is this in staging? I just redeployed with new logos in strapi admin and cant see it output. 

See attached images for more testing

![robotfrog](https://github.com/user-attachments/assets/330580fa-23e1-46c2-8a34-ada4a1cc50a4)
![lp](https://github.com/user-attachments/assets/98d5b7e9-a7fc-4049-8d42-300341fa7118)

**Comment by bonhokage06** [comment]
@developersteve  already updated staging.

![image](https://github.com/user-attachments/assets/e3f81f5c-ca4f-45c8-a83b-d4d34b627a4f)

**Comment by developersteve** [comment]
Perfect, yep i see it now.
